export const VALIDATE_TICKET = 'VALIDATE_TICKET'
export const VALIDATE_TICKET_SUCCESS = 'VALIDATE_TICKET_SUCCESS'
export const VALIDATE_TICKET_FAILURE = 'VALIDATE_TICKET_FAILURE'

export const ADD_CV = 'ADD_CV'
export const VALIDATE_CODE = 'VALIDATE_CODE'
export const VALIDATE_CODE_SUCCESS = 'VALIDATE_CODE_SUCCESS'
export const VALIDATE_CODE_FAILURE = 'VALIDATE_CODE_FAILURE'

export const GET_EXHIBITORS = 'GET_EXHIBITORS'
export const GET_EXHIBITORS_SUCCESS = 'GET_EXHIBITORS_SUCCESS'
export const GET_EXHIBITORS_FAILURE = 'GET_EXHIBITORS_FAILURE'

export const GET_INTERESTS = 'GET_INTERESTS'
export const GET_INTERESTS_SUCCESS = 'GET_INTERESTS_SUCCESS'
export const GET_INTERESTS_FAILURE = 'GET_INTERESTS_FAILURE'

export const GET_CONFERENCE = 'GET_CONFERENCE'
export const GET_CONFERENCE_SUCCESS = 'GET_CONFERENCE_SUCCESS'
export const GET_CONFERENCE_FAILURE = 'GET_CONFERENCE_FAILURE'
