export const VALIDATE_TICKET = 'VALIDATE_TICKET'
export const VALIDATE_TICKET_SUCCESS = 'VALIDATE_TICKET_SUCCESS'
export const VALIDATE_TICKET_FAILURE = 'VALIDATE_TICKET_FAILURE'

export const ADD_CV = 'ADD_CV'
export const VALIDATE_CODE = 'VALIDATE_CODE'
export const VALIDATE_CODE_SUCCESS = 'VALIDATE_CODE_SUCCESS'
export const VALIDATE_CODE_FAILURE = 'VALIDATE_CODE_FAILURE'

export const GET_EXHIBITORS = 'GET_EXHIBITORS'
export const GET_EXHIBITORS_SUCCESS = 'GET_EXHIBITORS_SUCCESS'
export const GET_EXHIBITORS_FAILURE = 'GET_EXHIBITORS_FAILURE'

export const GET_INTERESTS = 'GET_INTERESTS'
export const GET_INTERESTS_SUCCESS = 'GET_INTERESTS_SUCCESS'
export const GET_INTERESTS_FAILURE = 'GET_INTERESTS_FAILURE'

export const LOGOUT = 'LOGOUT'
export const GET_USER = 'GET_USER'

export const UPDATE_CV = 'UPDATE_CV'
export const UPLOAD_CV = 'UPLOAD_CV'

export const GET_CONFERENCE = 'GET_CONFERENCE'
export const GET_CONFERENCE_SUCCESS = 'GET_CONFERENCE_SUCCESS'
export const GET_CONFERENCE_FAILURE = 'GET_CONFERENCE_FAILURE'

export const GET_JOURNEYS = 'GET_JOURNEYS'
export const GET_JOURNEYS_SUCCESS = 'GET_JOURNEYS_SUCCESS'
export const GET_JOURNEYS_FAILURE = 'GET_JOURNEYS_FAILURE'

export const ADD_USERS_JOURNEYS = 'ADD_USERS_JOURNEYS'
export const ADD_USERS_JOURNEYS_SUCCESS = 'ADD_USERS_JOURNEYS_SUCCESS'
export const ADD_USERS_JOURNEYS_ERROR = 'ADD_USERS_JOURNEYS_ERROR'
