export const VALIDATE_TICKET = 'VALIDATE_TICKET'
export const VALIDATE_TICKET_SUCCESS = 'VALIDATE_TICKET_SUCCESS'
export const VALIDATE_TICKET_FAILURE = 'VALIDATE_TICKET_FAILURE'

export const VALIDATE_CODE = 'VALIDATE_CODE'
export const VALIDATE_CODE_SUCCESS = 'VALIDATE_CODE_SUCCESS'
export const VALIDATE_CODE_FAILURE = 'VALIDATE_CODE_FAILURE'
